# Generated by Django 4.2.30 on 2026-05-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-is_favorite', 'name']},
        ),
        migrations.AddField(
            model_name='contact',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
