# Generated by Django 4.2.30 on 2026-05-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_options_contact_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
