# Generated by Django 4.2.30 on 2026-06-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_options_contact_is_emergency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='has_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='reminder_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
