# Generated by Django 4.2.30 on 2026-06-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_birthday_contact_company_contact_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
